### ISSUE TITLE
Demo fails to build

### ISSUE THREAD

**Issue by IanAber** [aws-samples/iot-secure-tunneling-demo#12]
Whentrying to build this demo in Cloud9 there are many errors and the demo build fails to complete.

**Comment by sbSteveK** [comment]
Following the steps provided, I'm also running into build fails.

```
SyntaxError: /home/ubuntu/iot-secure-tunneling/config/ec2/key-pair.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1194:22)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/iot-secure-tunneling/cdk/lib/aws-iot-sec-tunnel-stack.ts:11:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/home/ubuntu/iot-secure-tunneling/cdk/node_modules/ts-node/src/index.ts:1608:43)

Subprocess exited with error 1

> aws-iot-sec-tunnel@0.1.0 build
> tsc

SyntaxError: /home/ubuntu/iot-secure-tunneling/config/ec2/key-pair.json: Unexpected end of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1194:22)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ubuntu/iot-secure-tunneling/cdk/lib/aws-iot-sec-tunnel-stack.ts:11:17)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/home/ubuntu/iot-secure-tunneling/cdk/node_modules/ts-node/src/index.ts:1608:43)

Subprocess exited with error 1
```

Also, the commands
``` 
cd ~/iot-secure-tunneling/
./bin/deploy.sh https://github.com/aws-samples/iot-secure-tunneling-demo
```
do not work as iot-secure-tunneling following the previous directions do not install into the home directory but instead into the ~/environment directory.

**Comment by pabloariasmora** [comment]
Resolved in #36. The stack has been modernized: CDK v1 → v2, Express 4 → 5, aws-sdk v2 → v3, Ubuntu 18.04 → 24.04. CDK synth produces a valid CloudFormation template and all packages build clean.
